name: "Get codes (genshinautogift)"
author: "MoonLGH & gamersindo1223"
description: "Update codes"

inputs:
    gh_token:
        description: "GitHub access token with Repo scope"
        default: ${{ github.token }}
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
        - name: cloning code checker
          run: git clone -b getcode https://github.com/gamersindo1223/genshinautogift/tree/getcode
          shell: bash
        - name: Set Node.js 18
          uses: actions/setup-node@v3
          with:
               node-version: 18
        - name: Install dependencies
          working-directory: ./genshinautogift
          run: npm i
          shell: bash
        - name: Run the script
          working-directory: ./genshinautogift
          run: node index.js
          shell: bash
          env:
              gh_token: ${{ inputs.gh_token }}