on:
  schedule:
    # Runs every day
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-codes:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install dependencies
        run: |
          cd main
          npm i
        shell: bash
      - name: Run the script
        run: |
          cd main
          node index.js
        shell: bash
        env:
          GHT_TOKEN: ${{ github.token }}
